// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCalendar: typeof import('vant/es')['Calendar']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
